### ISSUE TITLE
点击修改按钮后一片空白

### ISSUE THREAD

**Issue by Robotmaid** [easychen/checkchan-dist#21]
控制台报错为
`
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at N (2.16adb99e.chunk.js:1:820332)
    at R (2.16adb99e.chunk.js:1:820410)
    at e.value (main.d6ea93d8.chunk.js:1:23261)
    at ye (2.16adb99e.chunk.js:1:16911)
    at e.r (2.16adb99e.chunk.js:1:16605)
    at r.value (main.d6ea93d8.chunk.js:1:92006)
    at sc (2.16adb99e.chunk.js:1:2268545)
    at e (2.16adb99e.chunk.js:1:2268310)
    at ac (2.16adb99e.chunk.js:1:2268317)
    at 2.16adb99e.chunk.js:1:2280056
`
版本为Build.2022.06.26.14.42，浏览器为Edge 版本 103.0.1264.49 (正式版本) (64 位)

**Comment by easychen** [comment]
这个bug最近尝试修复了一下，你可以更新后再试试。
